general {
    lock_cmd=hyprdocked lock
    after_sleep_cmd=hyprdocked resume
}

listener {
    # Suspend after 30 seconds if hyprlock is active. Good for manual
    # locks and accidental wakes.
    timeout = 30
    on-timeout = sh -c 'pidof hyprlock >/dev/null && hyprdocked idle'
}

listener {
    timeout = 540
    on-timeout = hyprdocked lock
}


listener {
    timeout = 600 # 10 mins
    on-timeout = hyprdocked idle
}
